version: '3.8'
services:
  db:
    image: mysql:8.0
    platform: linux/arm64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maltalist
      MYSQL_USER: maltalist_user
      MYSQL_PASSWORD: M@LtApass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./maltalist-api/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
volumes:
  mysql_data:
